### ISSUE TITLE
Github getOrganization missing entries

### ISSUE THREAD

**Issue by jir-f** [wildland-sp/wildland-dashboard#31]
The response returned by the getOrganization has the following:

![screen shot 2018-01-17 at 11 14 54 pm](https://user-images.githubusercontent.com/13970855/35085269-c3d766e6-fbdc-11e7-8d9a-53258ce426ef.png)

However, the avatar entry and html_url entry are need to render the organization cards.

**Comment by DallasP9124** [comment]
@jir-f did we get this figured out yet? Have you been able to get this to work or do you need more endpoints?

**Comment by jir-f** [comment]
Yes. This is done.
